name: hahahahaha

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code.
      uses: actions/checkout@v2
      
#     - name: make new file
#       run: |
#         mkdir sealights
#         cd sealights
#       
#     - name: download sealights
#       run: |
#        iwr -OutFile sealights-dotnet-agent.zip -UseBasicParsing -Uri https://agents.sealights.co/dotnetcore/sealights-dotnet-agent-latest.zip
#        Expand-Archive .\sealights-dotnet-agent.zip -DestinationPath sl-dotnet-agent -Force
#        Write-Output "[Sealights] .NetCore Agent version is: $(Get-Content .\sl-dotnet-agent\version.txt)"
        
    - uses: 8BitJonny/gh-get-current-pr@2.1.3
      id: PR
        
    - name: github workflow variable context
      run: |
        $PR_NUM="$(system.pullRequest.pullRequestNumber)" 

        Write-Output "Build Reason =  ${{PR_NUM}}"
        
        Write-Output "PR_NUMBER = ${steps.PR.outputs.number}"
        
        Write-Output "REPO_URL  = ${{steps.PR.outputs.pr_url}}"
        
        Write-Output "PR_TARGET_BRANCH  = ${{steps.PR.outputs.pr_merged_at}}"
        
        Write-Output "PR_LAST_COMMIT  = ${{github.base_ref}}"
        
        Write-Output "PR = ${{github.event_name}}"
        

        
