name: hahahahaha

on:
  pull_request:
    branches: 
      - main
  
      
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    #runs-on: ubuntu-latest

        
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      
#     - name: make new file
#       run: |
#         mkdir sealights
#         cd sealights
#       
#     - name: download sealights
#       run: |
#        iwr -OutFile sealights-dotnet-agent.zip -UseBasicParsing -Uri https://agents.sealights.co/dotnetcore/sealights-dotnet-agent-latest.zip
#        Expand-Archive .\sealights-dotnet-agent.zip -DestinationPath sl-dotnet-agent -Force
#        Write-Output "[Sealights] .NetCore Agent version is: $(Get-Content .\sl-dotnet-agent\version.txt)"

#     - uses: 8BitJonny/gh-get-current-pr@2.1.3
#       id: PR

    
      - name: Log ENV Variables 
        env: 
          STEP_ENV: Available to only this step

        run: |
          echo "STEP_ENV: ${STEP_ENV}"


      - name: github workflow variable context
        env:
          SLDOMAIN: amdocs.sealights.com
          PR_NUMBER: ${{github.event.pull_request.number}}
          PR_TARGET_BRANCH: ${{github.head_ref}}
          PR_LAST_COMMIT: ${{ github.event.pull_request.head.sha }}
          REPO_URL: ${{github.repositoryUrl	}}
          
        run: |        
          echo "Build Reason =  ${{github.event_name}}"
          echo "PR_NUMBER = ${PR_NUMBER}"
          echo "PR_TARGET_BRANCH  = ${PR_TARGET_BRANCH}"
          echo "PR_LAST_COMMIT  = ${PR_LAST_COMMIT}"
          echo "REPO_URL  = ${REPO_URL}"
          echo "Domail = ${SLDOMAIN}"



          echo "PR_LAST_COMMIT  = ${{github.base_ref}}"

          echo "PR = ${{github.base_ref}}"
