# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Ginger Linux Build 

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.301'
      
      - name: printing
        run: |
          pwd
          ls -alt
    
      - name: Testing GingerUtilsTest
        run: dotnet test  Ginger/GingerUtilsTest --configuration Release --logger trx --verbosity=normal
    
    
    
    
    
#     - uses: actions/checkout@v3
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: 6.0.301
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
