name: ENV Variables 

on:
  pull_request:
    branches: 
      - main
  
      
  workflow_dispatch:

env: 
  WF_ENV: Available to all jobs 

jobs:
         
  log-env:
    runs-on: ubuntu-latest
    
    env:
      JOB_ENV: Available to all steps in log-env jobs
      
    steps:
      - name: Log ENV Variables 
        env: 
          STEP_ENV: Available to only this step 
          SLDOMAIN: amdocs.sealights.com
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          Write-Output "Build Reason =  ${{github.event_name}}"
          Write-Output "PR_NUMBER = ${{github.event.pull_request.number}}"
          Write-Output "PR_TARGET_BRANCH  = ${{github.head_ref}}"
          Write-Output "PR_LAST_COMMIT  = ${{ github.event.pull_request.head.sha }}"
          Write-Output "REPO_URL  = ${{github.repositoryUrl	}}"
          Write-Output "Domail = ${SLDOMAIN}"
          echo "Domail: ${SLDOMAIN}"
          Write-Output "PR_LAST_COMMIT  = ${{github.base_ref}}"
          Write-Output "PR = ${{github.base_ref}}"
          
  log-default-env: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Default ENV Variables 
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          
